name: Sync GitHub issues and pull requests with the governance system

on:
     workflow_dispatch: # allows manual triggering
     # schedule:
     # - cron: '55 * * * *'

jobs:
     sync_issues:
          environment: governance
          runs-on: ubuntu-latest
          permissions:
               contents: write
          steps:
               - name: 'Install gov4git from release'
                 uses: jaxxstorm/action-install-gh-release@v1.10.0
                 with:
                    repo: gov4git/gov4git # binary is added to the PATH as well
                    tag: ${{ vars.GOV4GIT_RELEASE }}
                    cache: enable
                    platform: linux
                    arch: arm64
               - name: 'Import issues and pull requests'
                 shell: bash
                 run: .scripts/sync_github.sh
                 env:
                    GOV_AUTH_USER: ${{ secrets.GOV_AUTH_USER }}
                    GOV_AUTH_TOKEN: ${{ secrets.GOV_AUTH_TOKEN }}
                    GOV_PUB_REPO: ${{ vars.GOV_PUB_REPO }}
                    GOV_PRIV_REPO: ${{ vars.GOV_PRIV_REPO }}
